### ISSUE TITLE
Technical comments classified as SPAM

### ISSUE THREAD

**Issue by KERNAMON** [php/policies#12]
First, we must say that we do not consider ourselves as experts in PHP, in any way.

We must also say that we are extremely interested in the further OOP development of PHP as a modern programming language (based on C, with more than 40 years of existence) for dev collaboration and remote work.

During the last few days, we have made a few technical comments on php/doc-en regarding some standing issues: **github.com/php/doc-en/issues/4077** was desmissed as not being relevant (we took the slap on the face, which is fine by us and we did not insist on that issue), but later on it was labeled as SPAM.

We must say that we do not agree with that classification and we have searched on your website, www.php.net/contact.php, any eMail address that could be used to mention this issue, but we neither believe that security@php.net nor php-webmaster@lists.php.net would suit that purpose, so we are posting here, on "policies".

We furthermore do not agree with the classification of SPAM, since other technical comments of ours were not labeled as SPAM, such as: github.com/php/doc-en/issues/4218 and github.com/php/doc-en/issues/4130 and github.com/php/doc-en/issues/3694 (where we found the Swiss gentleman without any given answer for more than 3 months and we hope that we were able to help him and php.net, somehow).

We must also add that several of our comments were added on your website (as examples and so on), which means that they were accepted as technically valid... and later on, they were deleted:

- www.php.net/manual/en/class.socket.php
- www.php.net/manual/en/function.filter-input-array.php
- www.php.net/manual/en/function.filter-var-array.php
- www.php.net/manual/en/language.types.value.php)

If they were correct or not, **it is up to you to decide** since you are the experts in PHP, but we do not believe that our eMail address being left on those webpages could constitute any form of SPAM, at all.

Best regards,

Saskia Ostermann Toutatis

**Comment by cmb69** [comment]
I've changed the classification to "off-topic". There are only a couple of options when hiding a comment, and that appears to be the most suitable; "spam" was certainly not quite right.

Anyhow, please raise those issues on the respective mailing list next time (in this case that would have been phpdoc@lists.php.net). The policies repository isn't quite suitable.

Thank you for your interest in PHP! :)

**Comment by KERNAMON** [comment]
Thank You.
